아이디 중복확인, 회원가입, 로그인 기능 구현,토근생성
wecode-bootcamp-korea/14-1st-O9O9-backend pull request #3
Opened 2020-11-20 02:17 UTC by Parkseungje

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
아이디중복확인 테이블 새로생성및 구현,
회원가입 기능구현,
로그인 기능 구현,
로그인시 토큰생성
		 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-20 08:49 UTC, lordmyshepherd requested changes

2020-11-20 08:49 UTC, lordmyshepherd commented on user/urls.py
> +    path('/signupview',SignUpView.as_view()),
endpoint에 'view' 용어가 포함되면, 불필요하게 url이 길어질 수 있습니다.
```suggestion
    path('/signup',SignUpView.as_view()),
```

2020-11-20 08:49 UTC, lordmyshepherd commented on user/views.py
> +#{ID:psj0810, password:12345, password_check:12345, name:박승제, phone_number:010-123-1234, email:}
9 line 데이터는 main에 merge되면 안되는 코드이므로 지워주세요~

2020-11-20 08:49 UTC, lordmyshepherd commented on user/views.py
> +#{ID:psj0810, password:12345, password_check:12345, name:박승제, phone_number:010-123-1234, email:}
```suggestion

```

2020-11-20 08:49 UTC, lordmyshepherd commented on user/views.py
> +                            return JsonResponse({'message':'중복된 ID입니다'}, status=400)
자원이 이미 존재하는 경우, 자원의 중복을 의미하는 duplicate status code는 `409` 입니다.

2020-11-20 08:49 UTC, lordmyshepherd commented on user/views.py
> +class DoubleCheckView(View):
해당 앤드포인트는 중복만 체크하는 앤드포인트이므로 CheckId table을 만들어서 유저의 상태를 관리해줄 필요가 없어 보입니다.
아래와 같이 중복 체크만 해주시면 됩니다.
```
    if re.match('^[a-zA-Z0-9]*$',data['ID']):
        return JsonResponse({'message':'영어 또는 숫자를 입력하세요'},status=400)

    if not (len(data['ID'])>=6) and (len(data['ID'])<=10):
        return JsonResponse({'message':'6~10자 사이의 영어 또는 숫자를 입력하세요'},status=400)   

     if User.objects.filter(username_id=data['ID']).exists():
         return JsonResponse({'message':'중복된 ID입니다.'}, status=409)

     return JsonResponse({'message':'가능한 ID입니다.'}, status=200)
```

2020-11-20 08:49 UTC, lordmyshepherd commented on user/views.py
> +class SignUpView(View):
회원가입 시에도 CheckId 를 사용하지 않고, username_id와 password를 사용하여 회원가입을 구현해주세요!

2020-11-20 11:12 UTC, Parkseungje commented on user/urls.py
> +    path('/signupview',SignUpView.as_view()),
수정완료

2020-11-20 11:12 UTC, Parkseungje commented on user/views.py
> +#{ID:psj0810, password:12345, password_check:12345, name:박승제, phone_number:010-123-1234, email:}
수정완료

2020-11-20 11:12 UTC, Parkseungje commented on user/views.py
> +#{ID:psj0810, password:12345, password_check:12345, name:박승제, phone_number:010-123-1234, email:}
수정완료

2020-11-20 11:12 UTC, Parkseungje commented on user/views.py
> +                            return JsonResponse({'message':'중복된 ID입니다'}, status=400)
수정완료

2020-11-23 12:09 UTC, Parkseungje commented on user/views.py
> +class DoubleCheckView(View):
수정완료

2020-11-23 12:09 UTC, Parkseungje commented on user/views.py
> +class SignUpView(View):
수정완료

2020-11-25 11:46 UTC, lordmyshepherd requested changes

2020-11-25 11:46 UTC, lordmyshepherd commented on review/views.py
> +class QuestionView(View):
슬제님 QuestionView <-- class 명 깔끔하고 가독성 좋게 잘 만들어주셨습니다!!
질문 리스트를 반환하는 class 이므로 QuestionsView로 수정해주세요~
```suggestion
class QuestionsView(View):
```

2020-11-25 11:46 UTC, lordmyshepherd commented on review/views.py
> +        return JsonResponse({'question_list':question_list},status=200)
현재는, question.question_type.id 로 연결된 가른 객체에 접근하게 되면 매번 database에서 데이터를 조회하게 됩니다.
select_related() method를 활용해서 database를 hitting하는 수를 줄일 수 있는게 공부해보고 적용해보세요~

2020-11-25 11:46 UTC, lordmyshepherd commented on review/views.py
> +        login_user = User.objects.get(id = request.user)
request에서 user instance를 가지고 와서 다시 User table에서 조회하는 이유가 있으신가요?

2020-11-25 11:46 UTC, lordmyshepherd commented on review/views.py
> +class QuestionInfoView(View):
해당 엔드포인트가 하는 역할을 잘 모르겠습니다. 설명해주실 수 있을까요?

2020-11-25 11:46 UTC, lordmyshepherd commented on review/views.py
> +            question   = Question.objects.get(id = question_number)
get() 호출시 매칭되는 객체가 없을 경우 UserDoesNotExist Error가 발생할 수 있으니 에러를 잡아주세요~

2020-11-25 11:46 UTC, lordmyshepherd commented on review/views.py
> +            answer = AnswerStatus.objects.get(id = data["answer"])
model에 default 값을 주면, 자동생성시 id를 할당해주시면 됩니다.

2020-11-26 02:17 UTC, lordmyshepherd commented
LGTM 👍

2020-11-26 02:17 UTC, merged