[이민영] 장바구니 품목 추가 기능구현
wecode-bootcamp-korea/14-1st-O9O9-backend pull request #4
Opened 2020-11-22 12:39 UTC by min00young

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- o9 쇼핑몰 사이트 장바구니 품목추가 기능 구현
		 
## 수정 사항들 자세한 내용
- cart안의 품목을 관리하는 CartItem을 통해서 user가 담은 상품과 수량을 관리합니다.
- 현재 운영중인 G9사이트에서는 유저가 동일상품을 장바구니에 다시 담을경우, 동일상품의 수량이 추가되지않고 처음담은 수량과 나중에 담은수량을 동일상품이 각각 구분해서 담겨지고 있어서, 동일상품을 장바구니에 다시 담을경우 동일상품의 수량이 추가되도록 코드를 추가했습니다.
- G9사이트에서는 여러항목을 장바구니에 담는 기능은 제공하지 않아서, 장바구니에 담는 상품은 1개로 지정했습니다.

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [v ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [v ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [v ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-11-24 02:37 UTC, lordmyshepherd requested changes

2020-11-24 02:37 UTC, lordmyshepherd commented on order/models.py
> +    order_number = models.CharField(max_length=100, null=True)
👍

2020-11-24 02:37 UTC, lordmyshepherd commented on order/models.py
> +        db_table = 'cartitems'
CarItem table이 여전히 필요한 이유가 있으신가요?

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +            product = CartItem.objects.get(product_id = product_id, user_id = user_id)
get() method를 사용해서 CartItem을 product_id와 user_id로 조회할 경우에, 
```
- 존재하지 않는 경우 어떤 에러가 발생할 수 있을까요?
- 중복되는 데이터가 존재할 경우 어떤 에러가 발생할 수 있을까요?
```

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +            return JsonResponse({'message': 'ITEM ADD SUCCESS'}, status = 200)
resource가 생성 되었을 경우, 상태코드는 201이 정확한 표현입니다.

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +        exist_product = CartItem.objects.filter(product_id = product_id, user_id = user_id)
CartItem.objects.filter() 함수가 실행되면 CartItem 인스턴스의 집합(QuerySet[<CartItem 1>, <CartItem 2>,.. ])으로 반환되는데, exist_product라고 하는 변수에 할당하고 있습니다.

변수를 명확하게 할당해주셔야 동료 개발자들이 봤을때, 혹은 내가 나중에 다시 이 코드를 봤을 때, 코드를 파악하기가 쉽습니다!
```suggestion
        cart_items = CartItem.objects.filter(product_id = product_id, user_id = user_id)
```

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +            }, status = 200)
코드는 잘 동작할 것 같습니다.
 **하지만 데이터가 20000개 정도만 되어도 DB에서 데이터를 조회할 경우, 시간이 오래걸릴 것 같습니다.**
좀 더 코드를 자세히 뜯어보면,

for문을 돌면서, 아래 get()가 호출될 때마다, DB를 hitting(조회)하게 됩니다.
```
Product.objects.get(id=cart_item['product_id']).name
```
```
Product.objects.get(id=cart_item['product_id']).price
```
```
Product.objects.get(id=cart_item['product_id']).thumbnail_image
```

우선,  cart_item에서 values()를 사용해서 dictionary를 반환받아서 사용하는 것이 아니라, `filter까지만 사용하여 instance로 반환받아서 CatItem 객체에서 Product 객체의 속성을 가져와서 리턴값을 다시 만들어보세요.`

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +    def patch(self, request):
patch를 구현할 경우 path parameter를 사용해서 앤드포인트를 구현해주세요!
```suggestion
    def patch(self, request, cart_item_id):
```

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +        cart_item          = CartItem.objects.get(id=cart_id)
get() method 사용시, cart_id에 해당하는 객체가 존재하지 않을 경우 어떤 에러가 발생할 수 있을까요?

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +    def delete(self, request):
path parameter를 사용해서 구현해주세요~
```suggestion
    def delete(self, request, cart_item_id):
```

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +        datas    = json.loads(request.body)
DELETE는 body에 데이터를 담지 않습니다.
```suggestion
        datas    = json.loads(request.body)
```

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +                return JsonResponse({'message': "KEY_ERROR"}, status = 400)
위에 이유 때문에 keyError를 잡아줄 필요도 없습니다!

2020-11-24 02:37 UTC, lordmyshepherd commented on order/views.py
> +            del_cart_item = CartItem.objects.get(id=cart_id)
get() 주의사항 위에 코멘트 남겨드렸습니다!

2020-11-24 02:37 UTC, lordmyshepherd commented on user/utils.py
> +        for_client_token = request.headers.get('authorization',None)
dictionary에 'authorization'이라는 key 값으로 접근할 때, 없는 경우 default로 None을 반환합니다.
그렇기 때문에, 두번째 인자로 None을 전달해줄 필요가 없습니다.
```suggestion
        access_token = request.headers.get('authorization')
```

2020-11-24 02:37 UTC, lordmyshepherd commented on user/utils.py
> +        for_client_token = request.headers.get('authorization',None)
변수명은 명사로 작성해주세요!

2020-11-24 02:37 UTC, lordmyshepherd commented on user/utils.py
> +        for_client_token = request.headers.get('authorization',None)
token의 종류가 많을 수 있습니다.
access_token? refresh_token? csrf_token?
그렇기 때문에 명확하게 어떤 token인지 명시해주셔야 됩니다!

2020-11-24 02:37 UTC, lordmyshepherd commented on user/utils.py
> +            user = User.objects.get(id=user_id['id'])
user_id 딕셔너리에 ['id']로 접근할 경우, key값이 존재하지 않는 경우 key error가 발생할 수 있습니다.

2020-11-24 04:53 UTC, min00young commented on order/models.py
> +        db_table = 'cartitems'
Cartitem table 삭제해서 다시 push예정입니다~!

2020-11-24 04:54 UTC, min00young commented on order/views.py
> +            return JsonResponse({'message': 'ITEM ADD SUCCESS'}, status = 200)
네~ create부분 201 코드로 수정하겠습니다!

2020-11-24 04:55 UTC, min00young commented on order/views.py
> +        exist_product = CartItem.objects.filter(product_id = product_id, user_id = user_id)
네, 알겠습니다!

2020-11-24 05:33 UTC, min00young commented on user/utils.py
> +        for_client_token = request.headers.get('authorization',None)
네, 변수명 수정했습니다~!

2020-11-24 07:41 UTC, min00young commented on order/views.py
> +            product = CartItem.objects.get(product_id = product_id, user_id = user_id)
존재하지 않는경우와 종복되는 데이타에 대한 예외처리 처리했습니다~!

2020-11-24 07:41 UTC, min00young commented on order/views.py
> +        datas    = json.loads(request.body)
넵!

2020-11-24 07:41 UTC, min00young commented on order/views.py
> +                return JsonResponse({'message': "KEY_ERROR"}, status = 400)
넵!

2020-11-24 07:42 UTC, min00young commented on order/views.py
> +            del_cart_item = CartItem.objects.get(id=cart_id)
넵!

2020-11-24 07:44 UTC, min00young commented on user/utils.py
> +            user = User.objects.get(id=user_id['id'])
키에러 부분 추가했습니다~!

2020-11-25 08:50 UTC, lordmyshepherd commented
LGTM 👍

2020-11-25 08:50 UTC, merged