Add : model 작성 및 CategoryView, ProductListView, SubCategoryView 작성
wecode-bootcamp-korea/14-1st-O9O9-backend pull request #5
Opened 2020-11-24 02:18 UTC by sungbolee

Add : model 작성 및 CategoryView, ProductListView, SubCategoryView 작성

2020-11-24 09:46 UTC, lordmyshepherd requested changes

2020-11-24 09:46 UTC, lordmyshepherd commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
프론트 코드가 올라온 것 같네요???

2020-11-24 09:46 UTC, lordmyshepherd commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
지원주세요~~

2020-11-24 09:46 UTC, lordmyshepherd commented on Brand.csv
> +삼립
csv파일은 github에 올라오지 않도록 gitignore에 추가해주세요~

2020-11-24 09:46 UTC, lordmyshepherd commented on db_uploader.py
> +import os
db_uploader 역시 github에 올라오지 않도록 gitignore에 추가해주세요~

2020-11-24 09:46 UTC, lordmyshepherd commented on order/models.py
> +        db_table = 'cartitems'
이 부분은 민영님이 작업하신 부분 아닌가요? 다른 pr에서도 같은 내용이 보여서요.

2020-11-24 09:46 UTC, lordmyshepherd commented on product/views.py
> +class CategoryView(View):
카테고리 리스트를 반환해주는 엔드포인트이므로, class명을 Categories로 만들어주시는게 좋을 것 같습니다.
```suggestion
class CategoriesView(View):
```

2020-11-24 09:46 UTC, lordmyshepherd commented on product/views.py
> +        return JsonResponse({"category": category_list}, status=200)
변수명을 정할때, 복수 단수도 맞춰주세요~
```suggestion
        return JsonResponse({"category": category_list}, status=200)
```

2020-11-24 09:46 UTC, lordmyshepherd commented on product/views.py
> +class ProductListView(View):
ProductsView로 class name을 수정해주시면 깔끔할 것 같아요!

2020-11-24 09:46 UTC, lordmyshepherd commented on product/views.py
> +    def get(self, request, maincategory_id):
Restful하게 앤드포인트를 구현하시려면, category는 filter 기능이므로 path parameter가 아니라 query parameter( query string)을 사용해서 구현해주세요!

2020-11-24 09:46 UTC, lordmyshepherd commented on product/views.py
> +        group_products = ProductGroup.objects.prefetch_related('product_set')
ProductGroup.objets.pre...()를 호출하면 반환되는 객체가 무엇일까요?
`product_groups = ...`

2020-11-24 09:46 UTC, lordmyshepherd commented on product/views.py
> +class SubCategoryView(View):
`class ProductListView(View)` class와 반복되는 로직이 많이 있습니다.
View를 하나로 합쳐주시고, maincategory_id와 subcategory_id를 query paramter를 이용해서 필터링할 수 있도록 코드를 수정해주세요.

2020-11-25 01:54 UTC, sungbolee commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
수정했습니다~

2020-11-25 01:54 UTC, sungbolee commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
수정했습니다~

2020-11-25 01:54 UTC, sungbolee commented on Brand.csv
> +삼립
수정했습니다~

2020-11-25 01:54 UTC, sungbolee commented on db_uploader.py
> +import os
수정했습니다~

2020-11-25 01:59 UTC, sungbolee commented on order/models.py
> +        db_table = 'cartitems'
제 models.py 에 변경 사항을 다 합쳐서 쓰기로 했는데 제가 따로 해야 하는 게 있을까요?

2020-11-25 01:59 UTC, sungbolee commented on product/views.py
> +        return JsonResponse({"category": category_list}, status=200)
수정했습니다~

2020-11-25 02:00 UTC, sungbolee commented on product/views.py
> +class ProductListView(View):
수정했습니다~

2020-11-25 02:02 UTC, sungbolee commented on product/views.py
> +        group_products = ProductGroup.objects.prefetch_related('product_set')
nongroup_products 과 묶어서
결국 불러오고 싶은 값이 Product 클래스의 속성들인데 그래도 product_groups 로 바꿔야 할까요?

2020-11-25 02:02 UTC, sungbolee commented on product/views.py
> +class SubCategoryView(View):
수정했습니다~

2020-11-25 09:22 UTC, lordmyshepherd requested changes

2020-11-25 09:22 UTC, lordmyshepherd commented on product/urls.py
> +    path('/categories', ProductsView.as_view()),
상품 정보를 받아오는 엔드포인트이므로 자원(resource) 중심으로 엔드포인트를 수정해주세요!
```suggestion
    path('/products', ProductsView.as_view()),
```

2020-11-25 09:22 UTC, lordmyshepherd commented on product/urls.py
> +    path('/categories/<int:product_id>', ProductDetailView.as_view())
마찬가지입니다!

2020-11-25 09:22 UTC, lordmyshepherd commented on product/views.py
> +        if main_category_id:
Django Q()를 사용하셔서, if문을 하나로 줄여보세요! 25~96까지 코드가 중복되요!

2020-11-25 09:22 UTC, lordmyshepherd commented on product/views.py
> +        product = Product.objects.select_related('maincategory', 'subcategory', 'brand', 'productgroup').get(id=product_id)
get()를 사용할 경우, 매칭되는 객체가 없는 경우 Error를 raise하게 됩니다. 그렇기 때문에 try, except로 에러를 잡아주세요!

2020-11-25 09:22 UTC, lordmyshepherd commented on product/views.py
> +        product = Product.objects.select_related('maincategory', 'subcategory', 'brand', 'productgroup').get(id=product_id)
selecte_related에 'more_information', 'seller_information'는 추가 안해주신 이유가 있으신가요?

2020-11-26 02:27 UTC, sungbolee commented on product/urls.py
> +    path('/categories', ProductsView.as_view()),
수정했습니다~

2020-11-26 02:27 UTC, sungbolee commented on product/urls.py
> +    path('/categories/<int:product_id>', ProductDetailView.as_view())
수정했습니다~

2020-11-26 02:27 UTC, sungbolee commented on product/views.py
> +        if main_category_id:
수정했습니다~

2020-11-26 02:27 UTC, sungbolee commented on product/views.py
> +        product = Product.objects.select_related('maincategory', 'subcategory', 'brand', 'productgroup').get(id=product_id)
수정했습니다~

2020-11-26 02:28 UTC, sungbolee commented on product/views.py
> +        product = Product.objects.select_related('maincategory', 'subcategory', 'brand', 'productgroup').get(id=product_id)
수정했습니다~

2020-11-26 04:28 UTC, lordmyshepherd requested changes

2020-11-26 04:28 UTC, lordmyshepherd commented on product/views.py
> +class ProductsView(View):
성보님 완전 고생하셨습니다!
중복 로직 완전히 제거하셨네요~ 👍👍👍👍👍

2020-11-26 04:28 UTC, lordmyshepherd commented on product/views.py
> +            nongroup_products = Product.objects.select_related('brand').filter(Q(maincategory=main_category_id) | Q(subcategory=sub_category_id), essential=False)
아래와 같은 방법으로 q객체를 더 동적으로 사용하실 수 있습니다~
```python
q = Q()
if main_category_id:
    q &= Q(main_category_id= main_category_id)
if sub_category_id:
    q &= Q(sub_category_id = sub_category_id)

nongroup_products = Product.objects.select_related('brand').filter(q), essential=False)
```

2020-11-26 04:28 UTC, lordmyshepherd commented on product/views.py
> +            product = Product.objects.select_related('maincategory', 'subcategory', 'brand', 'productgroup', 'more_information', 'seller_information', 'exchange').get(id=product_id)
👍 👍 👍 👍

2020-11-26 08:16 UTC, merged

2020-11-26 08:16 UTC, ulfrid commented
LGTM